Development
VishnuPrasad-1995/user-service pull request #7
Opened 2022-03-29 07:48 UTC by VishnuPrasad-1995

2022-03-31 05:59 UTC, Ramithags requested changes

2022-03-31 05:59 UTC, Ramithags commented on src/main/resources/application.properties
> +logging.file.name=D:/Spring/Assessment/user-service/src/logs/user_service.log
So your code will logs to your local only please avoid this and try to give relative path

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/service/UserServiceImpl.java
> +        User user1 = new User();
why are we calling this as user1 for objectName ?

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/service/UserServiceImpl.java
remove unwanted space

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/service/UserServiceImpl.java
> +        else{
Please format the code base

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/service/UserService.java
> +    UserDto createUser(UserRequest userRequest);
Do you want to specify as the UserDto as a naming convention ? can you rename this by avoiding Dto

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/dto/UserDto.java
>      private String phoneNumber;
Please add regex validation

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/dto/UserRequest.java
> +    private String email;
Add regex validation pattern

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/controller/UserController.java
>              throw new CustomCreateUserException("Syntax Error");
Is it a syntax error ? are you sure

2022-03-31 05:59 UTC, Ramithags commented on src/main/java/com/mavericsystems/userservice/constant/UserConstant.java
> +    public static final String EMAILALREADYEXIST = "Email Already exist : ";
Follow naming convention guide if possible https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2022-03-31 06:13 UTC, Ramithags reviewed
Can you please write unit tests

2022-04-08 17:41 UTC, VishnuPrasad-1995 commented
Changes are made as per reviewer, New pull request will be raised with modifications. So this PR is closed

2022-04-10 06:43 UTC, closed without merging